# NumPy
NumPy (or Numerical Python) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

### Installation Instructions

- conda install numpy
- pip3 install numpy

In [1]:
import numpy as np  # importing the required library

### Creating NumPy Arrays

In [2]:
my_list = [1,2,3]
vec = np.array(my_list)

In [3]:
vec 

array([1, 2, 3])

In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
np.arange(2,6)

array([2, 3, 4, 5])

In [7]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [8]:
np.arange(12,2,-1)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(start=1,stop=5,num=5)

array([1., 2., 3., 4., 5.])

### Generating arrays with random numbers

In [15]:
np.random.rand(4)  # uniform distribution 0 to 1 

array([0.4512351 , 0.76934283, 0.77930126, 0.38468943])

In [16]:
np.random.rand(2,2)

array([[0.22975172, 0.34635567],
       [0.46491386, 0.09044678]])

In [17]:
np.random.randn(4)   # standard normal distribution from -1 to +1, mean=0, var=1

array([ 1.35613967,  0.35282963, -1.94698138,  0.23979568])

In [18]:
np.random.randn(2,2)

array([[-0.28467771, -0.77693231],
       [-0.38753711,  0.34688971]])

In [19]:
np.random.randint(low=2,high=6) # a particular random number between [low,high)

2

In [20]:
np.random.randint(low=2,high=6,size=(5)) # with a specified shape

array([3, 4, 5, 3, 3])

In [21]:
np.random.randint(low=2,high=6,size=(5,5))

array([[3, 4, 5, 5, 2],
       [3, 5, 4, 5, 2],
       [4, 4, 3, 4, 5],
       [4, 5, 2, 5, 5],
       [5, 2, 4, 2, 4]])

### Methods of an array

In [22]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ran_arr = np.random.randint(0,50,10)
ran_arr

array([48, 29, 27, 23,  0, 37,  6, 19, 48, 38])

In [24]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
# arr.resize(4,6) changes array inplace

In [26]:
ran_arr.max()

48

In [27]:
ran_arr.min()

0

In [28]:
ran_arr.argmax()   # index of max

0

In [29]:
ran_arr.argmin()  # index of min

4

In [30]:
arr.shape

(24,)

In [31]:
arr.resize(6,4)

In [32]:
arr.shape

(6, 4)

In [33]:
arr.dtype

dtype('int32')