# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[5]

15

In [4]:
arr[1:5]

array([11, 12, 13, 14])

In [5]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [7]:
arr[1:6:2]  # with steps

array([11, 13, 15])

### Broadcast

In [8]:
# my_list = [1,2,3]
# my_list[:] = 100
# NORMAL LISTS CAN'T BROADCAST
# TypeError: can only assign an iterable

In [9]:
# numpy arrays can broadcast
arr[:] =100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr = np.arange(10,21)

In [11]:
sliced_arr = arr[0:6]
sliced_arr

array([10, 11, 12, 13, 14, 15])

In [12]:
sliced_arr[:] =100
sliced_arr

array([100, 100, 100, 100, 100, 100])

In [13]:
arr # changed in the original array, because it's a view/reference of the array

array([100, 100, 100, 100, 100, 100,  16,  17,  18,  19,  20])

In [14]:
arr = np.arange(10,21)

In [15]:
copy_arr = arr[0:6].copy()
copy_arr

array([10, 11, 12, 13, 14, 15])

In [16]:
copy_arr[:] =99
copy_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr  # doesn't change

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
matrix = np.random.randint(0,10,(3,3))
matrix

array([[0, 7, 2],
       [9, 7, 2],
       [4, 3, 4]])

In [19]:
matrix[0][0]  # using double brackets because list of lists

0

In [20]:
matrix[0,0]   # single bracket(row,column)

0

In [21]:
matrix[0:2,1:]   # sliced internal arrays

array([[7, 2],
       [7, 2]])

In [22]:
matrix[[0,2][1]]  # fancy way

array([4, 3, 4])

### Selection using logicals

In [23]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
condt = arr > 15

In [25]:
condt

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [26]:
arr[condt]   # only True selection

array([16, 17, 18, 19, 20])

In [27]:
arr[arr>15]

array([16, 17, 18, 19, 20])